version: '3'

services:
        login-service:
                build: ./login-service
                volumes:
                        - ./login-service:/usr/src/app
                ports:
                        - 5000:80
